image: ruby:2.6.3

variables:
  RAILS_ENV: test

# Cache gems in between builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor

.use-mysql: &use-mysql
  variables:
    MYSQL_DATABASE: redmine_test
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD: root
  services:
    - mysql:5.7

.use-pg: &use-pg
  variables:
    POSTGRES_DB: redmine_test
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
  services:
    - postgres:12.0

.prepare-for-test-mysql:
  before_script:
    - gem install bundler --no-ri --no-rdoc
    - cp config/database.yml.example config/database.yml
    - 'sed -i -e "s/host:.*$/host: mysql/g" config/database.yml'
    - 'sed -i -e "s/password:.*$/password: root/g" config/database.yml'
    - bundle install -j $(nproc) --path vendor --without development postgres minimagick
    - rake db:drop db:create db:migrate

.prepare-for-test-pg:
  before_script:
    - gem install bundler  --no-ri --no-rdoc
    - cp config/database.yml.example config/database.yml
    - 'sed -i -e "s/mysql2$/postgresql/g" config/database.yml'
    - 'sed -i -e "s/host:.*$/host: postgres/g" config/database.yml'
    - 'sed -i -e "s/password:.*$/password: root/g" config/database.yml'
    - 'sed -i -e "32,33d" config/database.yml'
    - bundle install -j $(nproc) --path vendor --without development minimagick mysql2
    - rake db:drop db:create db:migrate

before_script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor --without development postgres minimagick

rubocop:
  stage: test
  script:
    - bundle exec rubocop --parallel

test mysql:
  extends: .prepare-for-test-mysql
  <<: *use-mysql
  stage: test
  script:
    - bundle exec rake test

test pg:
  extends: .prepare-for-test-pg
  <<: *use-pg
  stage: test
  script:
    - bundle exec rake test
